[package]
name = "sonic-winnow"
version = "0.1.0"
authors = ["mrtambour <6724649+mrtambour@users.noreply.github.com>"]
edition = "2018"

[dependencies]
twitchchat = "0.4.2"
regex = "1.1.5"
reqwest = "0.9.14"


[features]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 2
lto = true